name: Build Tkinter Application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Match your local Python version
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk xvfb
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Load cached venv
      id: cached-poetry-deps
      uses: actions/cache@v3
      with:
        path: |
          .venv
          ~/.cache/pypoetry
        key: venv-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
    
    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root
        poetry install
    
    - name: Install PyInstaller via Poetry
      run: poetry add pyinstaller --group dev
    
    - name: Build with PyInstaller
      run: |
        poetry run pyinstaller GPGap-ubuntu.spec
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: GPGap-linux
        path: dist/
        if-no-files-found: error